#+title: Mythos Sysiphos

* Begriff der Absurdität
- Zwiespalt zwischen dem Menschen und seinem Leben
- Gefühl des Fremdseins im eigenen Leben
- beinhaltet auch die Sinnlosigkeit des Lebens

* Begriff der Hoffnung
- Ausweichen des Todes
- Hoffnung auf ein anderes Leben, das verdient werden muss
- Leben für ein Ideal, eine Idee, das dem Leben einen höheren Sinn gibt

* Zusammenhang zwischen dem Absurden und dem Selbstmord
- warum selbstmord?
  - Mensch fühlt sich fremd, hat keine Hoffnung


- ist der selbstmord die Lösung für das absurde?`
  - leuchtet ein den unbegreiflichen Zustand so schnell wie möglich aufzugeben
  - Selbstmörder oft selbst vom Sinn des Lebens überzeugt


- Widerspruch:
  - Häufig wird zu dem Schluss gekommen, dass Leben hätte keinen Sinn,  trotzdem wird dann nicht der entgültige Schluss daraus gezogen und sich das Leben genommen
  - liegt an dem Körper, der Vernichtung scheut

- Bringen sich Menschen konkret aufgrund der Sinnlosigkeit des Lebens, also der Absurdität um? Ist das der richtige Schritt der Absurdität zu entfliehen?
  -



* Kapitelnotizen
** Leben ohne Sinn?
Frage *Verlangt die Absurditaet, dass man ihr entflieht*, diese Frage soll logisch behandelt werden
- die erkenntnis, dass das Leben keinen Sinn  hat fuehrt nicht automatisch zu dem Urteil, dass sich das Leben nicht lohnt
- Die beiden Urteile "das Leben hat keinen Sinn" und "das Leben lohnt sich nicht" stehen nicht zwangslaeufig in einem Verhaeltnis miteinander

- ``
