#+TITLE: Paval Zorin-Kranich: Analysis I (Skript des Wintersemester 20/21, Universität Bonn)

empfohlene Literatur:

-[[file:buecher/terence_tao_analysis_I.org][t. Tao Analysis I]]  (hervorgehoben: logischen, mengentheoretischen Grundlagen)
- H. Amann, J.Enscher: Analysis I
- O. Forster: Übungsbuch zu Analysis 1 (enthält Aufgaben mit Lösungen, nützlich für die Prüfungsvorbereitung)
- S. Hildebrandt: Analysis 1 (enthält historische Informationen)


* 1 Natürliche Zahlen und vollständige Induktion
*** Definition 1.1: Die natürlichen Zahlen (Peano-Axiome für die natürlichen Zahlen)

Die natürlichen Zahlen ist ein *Tripel* $$( \mathbb{N}, 0, S)$$, wobei $$\mathbb{N}$$ eine Menge ist und $$S$$ eine *Abbildung* ([[file:begriffe.org::Funktionen][Funktion)]].

Das Tripel der natürlichen Zahlen erfüllt die folgenden Axiome:

-  $$P0: \ S 0\in \mathbb{N}$$

- $$PS: \ S: \mathbb{N}\rightarrow \mathbb{N}$$, $$S(n)$$ ist *der Nachfolger* von n.

- $$PInj: \ n\neq m \implies S(n) \neq S(m)$$
  -- Die funktion der Addition ist [[file:begriffe.org::Injektivität][injektiv]]

- $$PS\neq 0:\ \forall n \in \mathbb{N} (S(n) \neq 0)$$

- Induktionsprinzip: Sei P(n) Die Eigenschaft einer natürlichen Zahl, die die werte  *richtig* oder *falsch* annehmen kann. Es gilt:

  $$P(0) \land \forall n\in \mathbb{N} (P(n)\implies P(S(n)))\implies (\forall n\in\mathbb{N}(P(n))$$

*** Definition 1.2: wahre Aussagen
Eine Aussage ist ein Ausdruck, der die Werte *wahr* $$(1, \top)$$ oder *falsch* $$(0,\bot)$$ annehmen kann. Wenn A und B Aussagen sind, können aus ihnen neue Aussagen gebildet werden, die abhängig von den Werten von A und B bestimmte Werte annehmen.

*** Definition 1.3: Dezimalzahlen (informell)

$$ 1:= S(0), 2:= S(1), 3:= S(2), ...$$

$$\implies \mathbb{N} = {0,1,2,3, ...}$$

*Beispiele an Mengen, die nicht alle der Peano-Axiome erfüllen*

** 1.1 Addition
*** Definition 1.4: Addition
Eine *Addition* auf $$\mathbb{N}$$ ist eine Verknüfpung (Funktion) auf $$\mathbb{N}$$.
$$+: (\mathbb{N}\times \mathbb{N}) \rightarrow \mathbb{N}, (a,b) \mapsto a+b$$
-- Addition ist eine Funktion, die geordnete Paare natürlicher Zahlen natürlichen Zahlen zuordnet
Die Funktion der Addition hat *folgende Eigenschaften*:

$$0+: \forall n\in\mathbb{N}(0+n = n)$$
$$S+: \forall m, n\in\mathbb{N}(S(n) +m = S(n+m))$$
*** Lemma 1.5: (+0)
$$n+0 = n$$([[file:begriffe.org::Lemma/Theorem/Korollar][Lemma]])
**** Beweis
--Es die muss die Kommutativität von 0+ aus [[*Definition 1.4: Addition]] bewiesen werden.

*Beweis durch Induktion*:
Sei P(n) die Aussage n+0  = n.

*Induktionsanfang*
Es soll P(n) mit n = 0 gezeigt werden. Nach S+ gilt 0 + n = 0, demnach gilt 0 + 0 = 0. Daher gilt auch n+0 = n, wenn n=0.

*Induktionsschritt*
Es soll gezeigt werden, dass:
$$\forall n\in\mathbb{N} ( P(n) \implies P(S(n)) )$$

Um eine eigenschaft für alle $$n\in\mathbb{N}$$ zu zeigen, reicht es diese Eigenschaft für ein *festes* $$n\in\mathbb{N}$$ zu zeigen.

Sei $$n\in\mathbb{N}$$ fest.

Zu zeigen ist nun: $$P(n) \implies P(S(n))$$

Sei $$P(n)$$.-- $$P(n)$$ ist die *Induktionshypothese*, die angenommen wird,  zu zeigen ist jetzt, dass $$P(S(n))$$ aus dieser Induktionshypothese logisch folgt.


Nach S+ der [[*Definition 1.4: Addition][Eigenschaften der Addition]] gilt $$S(n) +0 = S(n+0)$$. nach der Induktionshypothese gilt  $$S(n+0) = S(n)$$, demnach gilt S(n) + 0 = S(n)$$, was zu beweisen war.
*** Lemma 1.6 (+1)
$$S(n) = n+1$$
**** Beweis
Beweis durch Induktion:

*Induktionsanfang*
sei n = 0.
Nach [[*Definition 1.3: Dezimalzahlen (informell)][der informellen Definition der Dezimalzahlen]], gilt, dass $$S(0) := 1$$. Nach [[*Definition 1.4: Addition][0+]] gilt $$1 = 0+1$$. Demnach gilt $$S(0) = 0+1$$

*Induktionsschritt*

*** Lemma 1.7: (+S)
$$ n+S(m) = S(n+m)$$
*** Lemma 1.8 (Kommutativität der Addition)
$$n+m = m+n$$
*** Lemma 1.9: (Assoziativität der Addition)
$$(m+n)+p = m+(n+p)$$
-- Es macht keinen Unterschied in welcher Reihenfolge summiert wird. Bereich in der Assoziativität nicht gilt: *Gleitkommazahlen*
**** Beweis
*Beweis durch Induktion*
Sei p und m sind fest.

Sei $$(m+n) +p = m+(n+p)$$ (Induktionshypothese)

Nach $$+S$$ und $$S+$$ gilt:
$$S((m+n)+p) = (S(m+n))+p = S(m+(n+p)) = (m + S( n+p))$$

$$(S(m+n)) + p = (m+(S(n+p)))$$ (erneut nach S+ und +S)

$$(m+S(n)) + p = m+ (S(n) + p) $$

*** Lemma 1.10: (Kürzungsregel der Addition)
$$\forall m,n,p \in\mathbb{N} (m+p = n+p \implies m=n)$$
**** Beweis
Es soll durch Induktion über p bewiesen werden, dass $$\forall m,n\in\mathbb{n}((m+p = n+p)\implies m=n)$$


*** Lemma 1.11:
$$\forall m,n\in\mathbb{N}(m+n=0\implies (m=0 \land n=0))$$

** 1.2 Multiplikation
Die Multiplikation ist eine Funktion auf $$\mathbb{N}$$.
$$\cdot : \mathbb{N}\times\mathbb{N}, (a,b)\mapsto ab$$
Die Funktion der Multiplikation erfüllt *folgende Eigenschaften*:
$$0\cdot: \  \forall n\in\mathbb{N} (0n=0)$$
$$S\cdot: \ \forall n\in\mathbb{N} (S(m)n =mn+n)$$

*** Lemma 1.12 (Distributivität der Multiplikation)
*** Lemma 1.12 b) (Kommutivität der Multiplikation)
*** Lemma 1.12 c) (Assoziativität der Multiplikation)
*** Lemma 1.13

**  1.3 Ordnung 
*** Lemma 1.13: transitive Ordnung


* 2 Mengenlehre
-


* Ganze, rationale und reelle Zahlen

* 4 Konvergenz
