#+title: Analysis1 Zorin Kranich


empfohlene Literatur:

- Terence Tao: Analysis I (hervorgehoben: logischen, mengentheoretischen Grundlagen)
- H. Amann, J.Enscher: Analysis I
- O. Forster: Übungsbuch zu Analysis 1 (enthält Aufgaben mit Lösungen, nützlich für die Prüfungsvorbereitung)
- S. Hildebrandt: Analysis 1 (enthält historische Informationen)




* 1 Natürliche Zahlen und vollständige Induktion
** Definition 1.1: Die natürlichen Zahlen (Peano-Axiome für die natürlichen Zahlen)

Die natürlichen Zahlen ist ein *Tripel* $$( \mathbb{N}, 0, S)$$, wobei $$\mathbb{N}$$ eine Menge ist und $$S$$ eine *Abbildung* ([[file:begriffe.org::Funktionen][Funktion)]].

Das Tripel der natürlichen Zahlen erfüllt die folgenden Axiome:

- $$0\in \mathbb{N}$$

- $$S: \mathbb{N}\rightarrow \mathbb{N}$$, $$S(n)$$ ist *der Nachfolger* von n.

- $$n\neq m \implies S(n) \neq S(m)$$

- $$ \forall n \in \mathbb{N} (S(n) \neq 0)$$

- Induktionsprinzip: Sei P(n) Die Eigenschaft einer natürlichen Zahl, die die werte  *richtig* oder *falsch* annehmen kann. Es gilt:

  $$P(0) \land \forall n\in \mathbb{N} (P(n)\implies P(S(n)))\implies (\forall n\in\mathbb{N}(P(n))$$

** Definition 1.2: wahre Aussagen
Eine Aussage ist ein Ausdruck, der die Werte *wahr* $$(1, \top)$$ oder *falsch* $$(0,\bot)$$ annehmen kann. Wenn A und B Aussagen sind, können aus ihnen neue Aussagen gebildet werden, die abhängig von den Werten von A und B bestimmte Werte annehmen.

** Definition 1.3: Dezimalzahlen (informell)

$$ 1:= S(0), 2:= S(1), 3:= S(2), ...$$

$$\implies \mathbb{N} = {0,1,2,3, ...}$$

*** Beispiele an Mengen, die nicht alle der Peano-Axiome erfüllen

** 1.1 Addition
*** Definition 1.4: Addition
Eine *Addition* auf $$\mathbb{N}$$ ist eine Verknüfpung (Funktion) auf $$\mathbb{N}$$.

$$+: (\mathbb{N}\times \mathbb{N}) \rightarrow \mathbb{N}, (a,b) \mapsto a+b$$

-- Addition ist eine Funktion, die geordnete Paare natürlicher Zahlen natürlichen Zahlen zuordnet


Die Funktion der Addition hat folgende Eigenschaften:

$$0+: \forall n\in\mathbb{N}(0+n = n)$$

$$S+: \forall m, n\in\mathbb{N}(S(n) +m = S(n+m))$$

*** Lemma 1.5:
[[file:begriffe.org::Lemma/Theorem/Korollar][Lemma]]: $$\forall n\in\mathbb{N}(n+0 = n)$$

--Es die muss die Kommutativität von 0+ aus [[*Definition 1.4: Addition]] bewiesen werden.

*Beweis durch Induktion*:
Sei P(n) die Aussage n+0  = n.

*Induktionsanfang*
Es soll P(n) mit n = 0 gezeigt werden. Nach S+ gilt 0 + n = 0, demnach gilt 0 + 0 = 0. Daher gilt auch n+0 = n, wenn n=0.

*Induktionsschritt*
